In [16]:
import geopy
from geopy.distance import vincenty
import pandas as pd

In [8]:
df = pd.read_csv('summary.csv')
df['distance'] = pd.Series(0.0, index=df.index)

In [10]:
center = (37.872105, -122.259470)
size = len(df)
def get_distance(lat, long):
    return vincenty(center, (lat, long)).miles

In [13]:
for i in range(size):
    df['distance'][i] = get_distance(df['latitude'][i], df['longitude'][i])

/Users/yikaluo/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [15]:
df.to_csv("add_dis.csv")

In [62]:
df1 = pd.read_csv("sum.csv")

In [63]:
df1

,address,bathrooms,bedrooms,latitude,longitude,sqft,price per room,distance,avg_rating,#cafes,#pubs
0,0 0,1,1,37.822124,-122.288089,965,2495,3.786,4.100,2,1
1,0 0,3,3,37.894473,-122.200520,3009,1966,3.573,4.025,2,0
2,0 0,0,1,37.901424,-122.306478,0,1700,3.270,4.050,3,1
3,0 0,0,3,37.836100,-122.263700,0,831,2.494,4.125,0,0
4,0 0,1,2,37.877021,-122.301865,800,975,2.342,4.025,3,1
5,0 0,1,2,37.890000,-122.295400,800,1375,2.320,3.950,3,0
6,0 0,0,1,37.861054,-122.291559,0,1800,1.913,4.075,5,1
7,0 0,1,1,37.899225,-122.265580,650,2000,1.900,4.075,3,1
8,0 0,0,2,37.845850,-122.262039,0,900,1.816,4.000,2,1
9,0 0,1,3,37.851560,-122.274721,1400,1120,1.644,4.000,3,0
10,0 0,0,2,37.851908,-122.275000,0,1550,1.631,3.975,4,0
11,0 0,1,3,37.849002,-122.260494,1350,1400,1.594,4.025,2,2
12,0 0,0,1,37.855864,-122.277167,0,1750,1.480,4.050,3,1
13,0 0,0,1,37.882441,-122.282424,0,2395,1.443,4.050,5,0
14,0 0,1,1,37.858126,-122.240379,400,1675,1.421,4.025,1,1
15,0 0,1,1,37.869940,-122.285180,508,2723,1.414,3.950,5,2
16,0 0,0,1,37.852408,-122.260022,0,1699,1.359,4.000,2,1
17,0 0,0,1,37.891800,-122.260400,0,2700,1.359,4.050,1,0
18,0 0,1,1,37.854526,-122.270480,500,1600,1.354,4.050,4,0
19,0 0,1,1,37.855881,-122.254486,1200,1500,1.152,4.000,2,0
20,0 0,0,4,37.881757,-122.275171,0,1125,1.086,4.000,6,1
21,0 0,1,1,37.867180,-122.278218,250,900,1.080,3.975,4,1
22,0 0,0,3,37.886125,-122.267180,0,1665,1.055,4.125,1,0
23,0 0,0,1,37.863000,-122.274900,0,2680,1.052,4.025,3,2
24,0 0,0,1,37.864012,-122.273369,0,2200,0.943,4.025,2,2
25,0 0,1,1,37.863911,-122.272253,500,1800,0.899,4.050,1,2
26,0 0,0,1,37.884169,-122.262383,0,1500,0.847,4.000,2,0
27,0 0,0,1,37.861959,-122.255988,0,1750,0.725,4.000,1,0
28,0 0,0,1,37.867096,-122.249594,0,2250,0.641,4.100,0,0
29,0 0,0,1,37.864250,-122.264593,0,1990,0.610,4.050,1,1
...,...,...,...,...,...,...,...,...,...,...,...
2107,telegraph at howe,0,2,37.857226,-122.260180,0,1200,1.027,4.025,3,0
2108,University at Bonar,0,1,37.869626,-122.287680,0,1550,1.552,3.925,1,0
2109,University at Bonar,0,1,37.869975,-122.287316,0,1500,1.529,3.950,4,2
2110,University ave at san pablo,1,2,37.869026,-122.292380,620,1350,1.812,3.950,0,0
2111,university ave at san pablo,1,2,37.869044,-122.291522,610,1350,1.765,4.000,2,2
2112,university ave at san pablo,1,2,37.869077,-122.291436,620,1350,1.760,3.950,5,2
2113,university ave at san pablo,1,2,37.869111,-122.291114,620,1350,1.742,3.925,1,0
2114,university ave at san pablo,1,2,37.869247,-122.290814,620,1350,1.725,4.000,2,1
2115,University Avenue,0,1,37.870226,-122.282380,0,2250,1.259,3.950,4,2
2116,University AVENUE,0,1,37.870991,-122.282038,0,2250,1.236,4.100,2,2
2117,University AVENUE,0,1,37.871263,-122.282038,0,2250,1.235,3.950,2,0
2118,University AVENUE,0,1,37.871525,-122.273380,0,2250,0.762,3.925,4,3
2119,University Avenue at Grant Street,1,2,37.871125,-122.275680,650,1250,0.889,3.950,4,1
2120,UNIVERSITY AVENUE at McGee Avenue,0,1,37.870825,-122.277880,0,2250,1.010,3.900,4,3
2121,University AVENUE at McGee Avenue,0,1,37.871296,-122.277811,0,2250,1.004,4.000,2,1
2122,University AVENUE at McGee Avenue,0,1,37.870890,-122.277510,0,2250,0.990,3.975,2,2
2123,Virginia at Euclid,1,1,37.878071,-122.260709,408,1250,0.417,4.150,6,0
2124,virginia at le roy,1,1,37.878173,-122.258542,750,3250,0.422,4.150,6,0
2125,Virginia St. at Le Roy Ave.,0,3,37.877925,-122.259280,0,1233,0.402,4.025,3,0
2126,Walnut at Cedar,0,2,37.875225,-122.294480,0,1647,1.926,3.975,4,0
2127,WALNUT at CEDAR,0,3,37.878715,-122.268283,0,1225,0.663,4.150,6,0
2128,Walnut at Cedar,0,2,37.878425,-122.268280,0,1647,0.650,4.150,6,0
2129,Walnut at Vine,1,1,37.879460,-122.268219,450,1700,0.697,4.025,2,0
2130,Walnut at Virginia,3,5,37.877004,-122.267768,1800,1080,0.566,3.950,5,1
2131,Walnut at Virginia,1,2,37.876903,-122.267747,1100,1600,0.561,4.000,3,0
2132,ward at ellsworth,0,3,37.860226,-122.262680,0,1198,0.838,4.025,2,0
2133,West St at 37th St,2,2,37.830427,-122.271480,1200,1775,2.949,4.000,1,0
2134,woolsey at college,0,2,37.853136,-122.252448,0,675,1.363,3.950,3,3
2135,Woolsey at King,0,2,37.850883,-122.274613,0,1175,1.682,4.000,3,0
2136,woolsey at king,0,2,37.850866,-122.274570,0,1175,1.681,4.000,3,0

In [64]:
from geopy.geocoders import Nominatim
geolocator = Nominatim()
def get_address(lat, long):
    return geolocator.reverse(str(lat) + ', ' + str(long)).address
for i in range(10):
    df1['address'][i] = get_address(df1['latitude'][i], df1['longitude'][i])

/Users/yikaluo/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [65]:
for i in range(10, 20):
    df1['address'][i] = get_address(df1['latitude'][i], df1['longitude'][i])

/Users/yikaluo/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [66]:
for i in range(20, 35):
    df1['address'][i] = get_address(df1['latitude'][i], df1['longitude'][i])

/Users/yikaluo/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [68]:
df1.to_csv("final.csv")